#!/bin/bash
PATH=/usr/bin:/primary/vari/software/pbsPretty/

################################################################################################################################
#  
#  Author     : Matthew Hoffman
#  Company    : Van Andel Institute
#  Description:
#  Send an email when a node is detected as having active processes
# 
################################################################################################################################

function check(){
  active_nodes=$(pbsnodez | grep "has active processes" | awk '{ printf "\n\n" $1 }')
  
  echo "$active_nodes" | while read -r line; do
    n=$(echo "$line" | cut -c 6-)
    if [[ "$n" != "" ]] && [[ "$n" != "node061" ]] && [[ "$n" != "node062" ]] && [[ "$n" != "node063" ]]; then 
      logger "$n is FREE but has active processes." 
    fi
  done 
}

check
