#!/bin/bash
/primary/vari/admin/tools/genomicsCoreFileMgmt/rsync_genomicscore.sh
/primary/vari/admin/tools/genomicsCoreFileMgmt/rsync_instruments_iscan.sh
/primary/vari/admin/tools/genomicsCoreFileMgmt/rsync_instruments_sequencing.sh
/primary/vari/admin/tools/genomicsCoreFileMgmt/rsync_instruments_novaseq.sh
/primary/vari/admin/tools/genomicsCoreFileMgmt/rsync_instruments_iseq.sh
/primary/vari/admin/tools/genomicsCoreFileMgmt/rsync_instruments_minion.sh
/primary/vari/admin/tools/genomicsCoreFileMgmt/notifyFileAge.pl
/primary/vari/admin/tools/genomicsCoreFileMgmt/moveFilesToAWSStaging.pl
