#!/bin/bash

################################################################################################################################
#  
#  Author     : Matthew Hoffman
#  Company    : Van Andel Institute
#  Description: 
#  End all remaining user processes on a node when a job ends if and only if it was the only job on a node.
#  Send a message to the syslog.
#
################################################################################################################################

joblist=$(/cm/shared/apps/torque/6.0.2/bin/pbsnodes $HOSTNAME | grep "jobs = " | awk '{print $3}' | cut -c 3-)
if [[ "$joblist" == "$1" ]]; then
  killall -u $2
  process_list=$(pgrep -u $2 | xargs)
  logger PBS_CLEAN_NODE Ended $process_list owned by $2 on $HOSTNAME
fi
