#!/bin/bash

################################################################################################################################
#  
#  Author     : Matthew Hoffman
#  Company    : Van Andel Institute
#  Description: 
#  End all remaining user processes on a node when a job ends if and only if it was the only job on a node.
#  Send a message to the syslog if there were processes outside of the job.
#
################################################################################################################################

joblist=$(/cm/shared/apps/torque/6.0.2/bin/pbsnodes $HOSTNAME | grep "jobs = " | awk '{print $3}' | sed -e 's/.master.cm.cluster//g' -e 's/[[:digit:]]\+\///g' -e 's/[[:digit:]]\+\-//g')
logger PBS_CLEAN_NODE called with args: $1 $2  and detected node is running job $joblist
if [[ "$joblist" == "$1" ]]; then
  process_list=$(pgrep -u $2 | xargs)
  killall -u $2
  if [[ "$process_list" != "" ]]; then
    logger PBS_CLEAN_NODE Ended $process_list owned by $2 on $HOSTNAME
  fi
fi
logger PBS_CLEAN_NODE Done cleaning up
exit 0

