#!/bin/bash

################################################################################################################################
#  
#  Author     : Matthew Hoffman
#  Company    : Van Andel Institute
#  Description: 
#  Automatically detect, log and end high memory/CPU processes on the head node
#   ex: ./detect_high_intensity_processes -m 25, sets the percentage to 25%  total mem (default is 25%)
#   ex: ./detect_high_intensity_processes -c 15, sets the percentage to 15% of the CPU (default is 20%)
#   ex: ./detect_high_intensity_processes -t 5, sets the time allowed to 5 minutes (default is 5)
#   the -e option is required to automatically end processes (not set by default)                                                                     
#   the -a option is required to alert users (not set by default)
#   the -v option enables additional output to the logs
#
################################################################################################################################

########################################
# Check for high intensity processes
# 
# @param: string, the type of resource
#           ex: "CPU", "MEM"
########################################
function process_ps(){

  while read -r line; do

    arr=($line)
    user=${arr[0]}
    uid=${arr[1]}
    pid=${arr[2]}
    fname=${arr[3]}
    cpu=${arr[4]}
    mem=${arr[5]}
    
    if [[ "$1" == "MEM" ]]; then
      check=$mem
      max="$PERCENTAGE_MEM"
      type="memory"
      check=$(echo "$check" | tr -d g)
    else
      check=$cpu
      max="$PERCENTAGE_CPU"
    fi
    
    [ -z "$max" ] && max=999999999
    
    # round float to int  
    check=$(printf "%.0f" "$check")
    
    host=$(hostname)
    line="$user $fname $pid"

    # if the the process is using more of the resource than allowed and user is not a
    # system user, alert the user and send to system log 
    if [[ "$check" -ge "$max" ]] && [[ "$uid" -gt 500 ]]; then
      if [[ "$ALERT_USER" -eq 1 ]]; then
        first_name=$(echo ${user^} | cut -d "." -f 1)
        
        msg="Hello $first_name,\n\n"
        msg1="Your process $fname ($pid) was automatically detected using more $type than allowed for a user process on $host.hpc.vai.org. "
        msg2="$host.hpc.vai.org is a shared resource intended solely for job submission, "
        msg3="all high intensity processes should be run on a compute node. "
        msg4="Your process will be terminated soon. To prevent any loss of data from sudden termination "
        msg5="please end $fname ($pid) and help ensure that shared HPC resources are used fairly.\n\n"
        msg6="HPC team\nhpc3@vai.org"
        
        send="$msg$msg1$msg2$msg3$msg4$msg5$msg6"
        #grep -qF -- "$line" "$file" || printf "$send" | mail -v -s "$fname ($pid)" $user@vai.org,matthew.hoffman@vai.org
        grep -qF -- "$line" "$file" || printf "$send" | mail -v -s "$fname ($pid)" matthew.hoffman@vai.org
      fi

      d=$(date +%Y%m%d%H%M)
      
      grep -qF -- "$line" "$file" || log "High intensity process $fname ($pid) owned by $user is using more $type than allowed on $host."
      grep -qF -- "$line" "$file" || echo "EVENT_SEVERITY_WARNING:Process $fname ($pid) owned by $user is using more $type than allowed on $host." > /var/spool/cmd/eventbucket
      grep -qF -- "$line" "$file" || echo "$line $d" >> "$file"
    fi

  done <<< $(top -o %$1 -b -n 2 | head -n 17 | sed 1,7d)
}

function end(){
  while read name
  do
    arr=($name)
    user=${arr[0]}
    fname=${arr[1]}
    pid=${arr[2]}
    t=${arr[3]}

    date=$(date +%Y%m%d%H%M)

    date=${date#0}
    t=${t#0}

    dif=$(($date-$t))

    if [[ "$dif" -ge "$ALLOWED_TIME" ]]; then
      
      sed -i "/$pid/d" $file 
      
      if [[ "$END" -eq 1 ]]; then
        log "Automatically ended high intensity process: $fname ($pid) owned by $user"
        killall $fname -u $user
      fi
    fi

  done < $file
}

function log(){
  logger_path="/usr/bin/logger"
  if [[ "$VERBOSE" -eq 1 ]]; then
    $logger_path $1
  fi
}

# POSIX Variable require for getopts
OPTIND=1                                                                        

# read in command line arguments
while getopts "aev?c:t:m:" opt; do                                                
  case "$opt" in                                                                
    e)
      END=1    
      ;;
    a)
      ALERT_USER=1
      ;;
    v)
      VERBOSE=1
      ;;
    c)                                                                          
      PERCENTAGE_CPU=$OPTARG                                                        
      ;;
    m)
      PERCENTAGE_MEM=$OPTARG
      ;;                                                                       
    t)                                                                          
      ALLOWED_TIME=$OPTARG                                                        
      ;;                                                                        
    *)                                                                          
      echo >&2 "Invalid argument(s): $1"                                        
      exit 0                                                                    
      ;;                                                                        
  esac                                                                          
done                                                                            
                                                                                
shift $((OPTIND-1))                                                             
[ "$1" = "--" ] && shift  

file=".ps.txt"

# set variables to default values if not set on the command line
[ -z "$PERCENTAGE_MEM" ] && PERCENTAGE_MEM=25
[ -z "$PERCENTAGE_CPU" ] && PERCENTAGE_CPU=20
[ -z "$ALLOWED_TIME" ] && ALLOWED_TIME=5
[ -z "$VERBOSE" ] && VERBOSE=0
[ -z "$END" ] && END=0
[ -z "$ALERT_USER" ] && ALERT_USER=0

########
# Run
########

log "Running detect_high_intensity_processes with ALERT_USER:$ALERT_USER END_PROCESS:$END MAX_MEM:$PERCENTAGE_MEM MAX_CPU:$PERCENTAGE_CPU TIME:$ALLOWED_TIME min"

process_ps "MEM"
process_ps "CPU"

end
